/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProvidedService } from '../../models/provided-service';

export interface GetServiceById$Params {
  id: number;
}

export function getServiceById(http: HttpClient, rootUrl: string, params: GetServiceById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProvidedService>> {
  const rb = new RequestBuilder(rootUrl, getServiceById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProvidedService>;
    })
  );
}

getServiceById.PATH = '/api/services/{id}';
