/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupportResponse } from '../../models/support-response';

export interface AddResponse$Params {
  refugeeSupportId: number;
      body: SupportResponse
}

export function addResponse(http: HttpClient, rootUrl: string, params: AddResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportResponse>> {
  const rb = new RequestBuilder(rootUrl, addResponse.PATH, 'post');
  if (params) {
    rb.path('refugeeSupportId', params.refugeeSupportId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportResponse>;
    })
  );
}

addResponse.PATH = '/api/support-responses/add/{refugeeSupportId}';
