/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefugeeSupport } from '../../models/refugee-support';

export interface GetAllRefugeeSupports$Params {
}

export function getAllRefugeeSupports(http: HttpClient, rootUrl: string, params?: GetAllRefugeeSupports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RefugeeSupport>>> {
  const rb = new RequestBuilder(rootUrl, getAllRefugeeSupports.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RefugeeSupport>>;
    })
  );
}

getAllRefugeeSupports.PATH = '/api/refugee-support/all';
