/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefugeeSupport } from '../../models/refugee-support';

export interface GetRefugeeSupportsByStatus$Params {
  status: string;
}

export function getRefugeeSupportsByStatus(http: HttpClient, rootUrl: string, params: GetRefugeeSupportsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RefugeeSupport>>> {
  const rb = new RequestBuilder(rootUrl, getRefugeeSupportsByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RefugeeSupport>>;
    })
  );
}

getRefugeeSupportsByStatus.PATH = '/api/refugee-support/status/{status}';
