/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefugeeSupport } from '../../models/refugee-support';

export interface UpdateRefugeeSupport$Params {
  id: number;
      body: RefugeeSupport
}

export function updateRefugeeSupport(http: HttpClient, rootUrl: string, params: UpdateRefugeeSupport$Params, context?: HttpContext): Observable<StrictHttpResponse<RefugeeSupport>> {
  const rb = new RequestBuilder(rootUrl, updateRefugeeSupport.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefugeeSupport>;
    })
  );
}

updateRefugeeSupport.PATH = '/api/refugee-support/update/{id}';
