/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Case } from '../../models/case'; 


export interface GetAllCases$Params {
}

export function getAllCases(http: HttpClient, rootUrl: string, params?: GetAllCases$Params, context?: HttpContext): Observable<StrictHttpResponse<Case[]>> {
  const rb = new RequestBuilder(rootUrl, getAllCases.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<Case[]>) => {
      return r as StrictHttpResponse<Case[]
      >;
    })
  );
}

getAllCases.PATH = '/api/cases';
