/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Association {
  associationDescription?: string;
  associationId?: number;
  foundingDate?: string;
  name?: string;
  category?: string;
  
}
