/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Case } from '../models/case';
import { RefugeeSupport } from '../models/refugee-support';
export interface Document {
  caseRef?: Case;
  createdDate?: string;
  data?: Array<string>;
  documentId?: number;
  fileName?: string;
  fileType?: string;
  name?: string;
  path?: string;
  refugeeSupport?: RefugeeSupport;
  type?: string;
  verified?: boolean;
}
