/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RefugeeSupport } from '../models/refugee-support';
export interface ProvidedService {
  description?: string;
  name?: string;
  refugeeSupports?: Array<RefugeeSupport>;
  serviceId?: number;
}
