/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface SupportResponse {
  agent: User;
  helpRequestResp: string;
  questionResp: string;
  responseDate: string;
  shelterRequestResp?: string;
  supportRespId?: number;
}
