/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Testimonial {
  content?: string;
  datePost?: string;
  testimId?: number;
  sentiment?: string;
}
