/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Association } from '../models/association';
export interface User {
  associations?: Array<Association>;
  birthDate?: string;
  email?: string;
  password?: string;
  role?: 'ADMIN' | 'VOLUNTEER' | 'REFUGEE' | 'MEMBER';
  userId?: number;
  username?: string;
}
