/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Association } from '../../models/association';

export interface CreateAssociation$Params {
      body: Association
}

export function createAssociation(http: HttpClient, rootUrl: string, params: CreateAssociation$Params, context?: HttpContext): Observable<StrictHttpResponse<Association>> {
  const rb = new RequestBuilder(rootUrl, createAssociation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Association>;
    })
  );
}

createAssociation.PATH = '/api/associations';
